apiVersion: v1
kind: Service
metadata:
  name: remitpulse-countries
  annotations:
    servicePatterns: "country"
    isDiscoverable: "true"
spec:
  selector:
    app: remitpulse-countries
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP